version: "3"
networks:
  geoserver-network:
    driver: bridge
services:
  postgres:
    image: postgis/postgis
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - 5432
    env_file:
      - ./postgres/postgres.env
    volumes:
      - pg_data:${PGDATA:-/var/lib/postgresql/data}:rw
      - ./postgres/01-init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh
    networks:
      - geoserver-network

  geoserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GEOSERVER_WEBAPP_SRC: "https://build.geoserver.org/geoserver/main/geoserver-main-latest-war.zip"
    container_name: geoserver
    depends_on:
      postgres:
        condition: service_healthy    
    ports:
      - 9281:8080
    environment:
      - GEOSERVER_LOG_DIR=${GEOSERVER_LOG_DIR}
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CONFIG_DIR=${GEOWEBCACHE_CONFIG_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - NETCDF_DATA_DIR=${NETCDF_DATA_DIR}
      - GRIB_CACHE_DIR=${GRIB_CACHE_DIR}        
    volumes:
      - logs:${GEOSERVER_LOG_DIR}
      - datadir:${GEOSERVER_DATA_DIR}
      - gwc_config:${GEOWEBCACHE_CONFIG_DIR}
      - gwc:${GEOWEBCACHE_CACHE_DIR}
      - netcfd:${NETCDF_DATA_DIR}
      - grib_cache:${GRIB_CACHE_DIR}
    networks:
      - geoserver-network
  
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./geoserver.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
    - 80:80
    depends_on:
      - geoserver
    networks:
      - geoserver-network

volumes:
  pg_data:
  logs:
  datadir:
  gwc_config:
  gwc:
  netcfd:
  grib_cache:
